server:
  port: 11000

## 服务实例名
spring:
  application:
    name: gate-way
  main:
    web-application-type: reactive

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   # 是否和服务注册与发现组件结合，设置为 true 后可以直接使用应用名称调用服务
      # 路由（routes：路由，它由唯一标识（ID）、目标服务地址（uri）、一组断言（predicates）和一组过滤器组成（filters）。filters 不是必需参数。）
      routes:
        # 路由标识（id：标识，具有唯一性）   简单尝试route_simple
        - id: producer-id
          # 目标服务地址（uri：地址，请求转发后的地址）
          uri: lb://CONSUMER-SERVER
          # 路由条件（predicates：断言，匹配 HTTP 请求内容）
          predicates:
            ## 转发地址格式为 uri/archive
            - Path=/demo/**

# eureka 配置信息
eureka:
  instance:
    # 使用 ip 代替实例名
    prefer-ip-address: true
    # 实例的主机名
    hostname: ${spring.cloud.client.ip-address}
    # 实例的 ID 规则
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      # 注册中心地址
      defaultZone: http://localhost:8090/eureka/
logging:
  charset:
    console: utf-8
  level:
      org.springframework.cloud.gateway: TRACE
      org.springframework.http.server.reactive: DEBUG
      org.springframework.web.reactive: DEBUG
      reactor.ipc.netty: DEBUG
